### PR TITLE
Changed the tier text to an image/button

### PR DESCRIPTION
**Pull request by DiversenSato**
Replaces the "Tier ??" with a button that matches the level's tier. If the level is unrated or the data isn't fetched yet, the button sprite will be the mod icon/unrated image. All images are source directly from the GDDL Discord server.
When the button is clicked, it will create a pop-up that displays the level's tier and enjoyment up to 2 decimal precision. It will also show the total amount of submissions.

-Diversion, developer of gdladder.com

### CODE REVIEW

**Comment by DiversenSato** [comment]
image
Might need to align the button to the demon face and not just the entire sprite tho

**Comment by B1rtek** [comment]
Oh my god, this is amazing

**Comment by B1rtek** [comment]
I encountered a crash while testing this, but I wasn't able to recreate it afterwards and the log didn't point to the mod being at fault so everything looks good to me, I'll merge it into main (I should add a dev branch or sth tbh) and edit about.md to mention your contributions

**Comment by DiversenSato** [comment]
This was my hello world c++ project so it's entirely possible there is a bug somewhere

**Pull request merged**
